### ISSUE TITLE
Problems parsing extra spaces between column names (e.g., PayPal)

### ISSUE THREAD

**Issue by joebowbeer** [xlson/groovycsv#30]
In CSV files exported from PayPal, the column names in the first line are separated by ", "

Sample:

> Date, Time, Time Zone, Name, Type, Status, Currency, Amount, Receipt ID, Balance, 

When groovycsv parses these, the second and subsequent column names contain a leading space.

I expect that the leading space would be stripped, or that there would at least be some option to strip leading whitespace from the column names.

**Comment by xlson** [comment]
I'll think about it. We couldn't strip the leading whitespace by default as that could break existing code but I guess we could do a feature to enable stripping.
