### ISSUE TITLE
Publish a new release to Maven

### ISSUE THREAD

**Issue by smartdreamer** [xlson/groovycsv#31]
There hasn't been a new release since 2012 (to maven). The last version is 1.0 and lack a few bug fixes and enhancements. Could you publish a new release to Maven?
Thanks

**Comment by xlson** [comment]
Sorry about that. Currently the release code isn't working, probably due to a few updates to Gradle since 2012. I'll look into it.

**Comment by xlson** [comment]
Live now as com.xlson.groovycsv:groovycsv:1.1
