### ISSUE TITLE
Unable to do the build

### ISSUE THREAD

**Issue by nmrao** [xlson/groovycsv#33]
Cloned to the master.
and running ./gradlew --debug, stacktrace below.
Am I missing anytihng?

15:56:10.775 [DEBUG] [org.gradle.messaging.remote.internal.TcpOutgoingConnector] Found loop-back addresses: [/0:0:0:0:0:0:0:1%1, /127.0.0.1].
15:56:11.418 [DEBUG] [de.huxhorn.gradle.pgp.PgpSigner] Added BouncyCastleProvider.
15:56:11.446 [DEBUG] [de.huxhorn.gradle.pgp.PgpPlugin] Created PgpSigner instance.
15:56:11.923 [DEBUG] [org.gradle.configuration.BuildScriptProcessor] Timing: Running the build script took 2.779 secs
15:56:11.933 [ERROR] [org.gradle.BuildExceptionReporter] 
15:56:11.937 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:56:11.939 [ERROR] [org.gradle.BuildExceptionReporter] 
15:56:11.940 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
15:56:11.941 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/opt/softwares/workspace/otherprojects/groovycsv/build.gradle' line: 18
15:56:11.942 [ERROR] [org.gradle.BuildExceptionReporter] 
15:56:11.942 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:56:11.943 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'groovycsv'.
15:56:11.946 [ERROR] [org.gradle.BuildExceptionReporter] Cause: Could not find method maven() for arguments [build_gr4fdlqlq7963u3c5ul17a57$_run_closure1_closure11@518e322b] on root project 'groovycsv'.
15:56:11.947 [ERROR] [org.gradle.BuildExceptionReporter] 
15:56:11.948 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:56:11.950 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'groovycsv'.
15:56:11.951 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.groovy.scripts.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:51)
15:56:11.952 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:127)
15:56:11.952 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
15:56:11.953 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultProjectEvaluator.evaluate(DefaultProjectEvaluator.java:38)
15:56:11.954 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:487)
15:56:11.954 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:71)
15:56:11.955 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:23)
15:56:11.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:21)
15:56:11.957 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuildConfigurer.java:38)
15:56:11.958 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuildConfigurer.java:35)
15:56:11.959 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:463)
15:56:11.960 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:458)
15:56:11.961 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
15:56:11.962 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:141)
15:56:11.963 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
15:56:11.964 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:80)
15:56:11.964 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.RunBuildAction.execute(RunBuildAction.java:41)
15:56:11.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.RunBuildAction.execute(RunBuildAction.java:27)
15:56:11.966 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.ExceptionReportingAction.execute(ExceptionReportingAction.java:32)
15:56:11.967 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.ExceptionReportingAction.execute(ExceptionReportingAction.java:21)
15:56:11.967 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory.java:219)
15:56:11.968 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory.java:203)
15:56:11.969 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.execute(Main.java:55)
15:56:11.970 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.main(Main.java:40)
15:56:11.970 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.ProcessBootstrap.runNoExit(ProcessBootstrap.java:46)
15:56:11.971 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.ProcessBootstrap.run(ProcessBootstrap.java:28)
15:56:11.972 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:24)
15:56:11.972 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
15:56:11.973 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.Wrapper.execute(Wrapper.java:87)
15:56:11.974 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:37)
15:56:11.975 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.internal.MissingMethodException: Could not find method maven() for arguments [build_gr4fdlqlq7963u3c5ul17a57$_run_closure1_closure11@518e322b] on root project 'groovycsv'.
15:56:11.975 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:60)
15:56:11.976 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
15:56:11.977 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:106)
15:56:11.978 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
15:56:11.978 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.groovy:68)
15:56:11.979 [ERROR] [org.gradle.BuildExceptionReporter] 	at build_gr4fdlqlq7963u3c5ul17a57$_run_closure1.doCall(/opt/softwares/workspace/otherprojects/groovycsv/build.gradle:18)
15:56:11.980 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:61)
15:56:11.980 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:31)
15:56:11.981 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.repositories(AbstractProject.java:889)
15:56:11.982 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:158)
15:56:11.983 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:93)
15:56:11.983 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
15:56:11.984 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.groovy:68)
15:56:11.985 [ERROR] [org.gradle.BuildExceptionReporter] 	at build_gr4fdlqlq7963u3c5ul17a57.run(/opt/softwares/workspace/otherprojects/groovycsv/build.gradle:16)
15:56:11.986 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.groovy.scripts.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:49)
15:56:11.986 [ERROR] [org.gradle.BuildExceptionReporter] 	... 29 more
15:56:11.987 [ERROR] [org.gradle.BuildExceptionReporter] 
15:56:11.988 [LIFECYCLE] [org.gradle.BuildResultLogger] 
15:56:11.988 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
15:56:11.989 [LIFECYCLE] [org.gradle.BuildResultLogger] 
15:56:11.990 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 4.084 secs

**Comment by xlson** [comment]
Most likely the issue was casued by GroovyCSV using a very old version of Gradle. It's updated to the latest one now and show work.
