### ISSUE TITLE
Problem when header row has an extra separator

### ISSUE THREAD

**Issue by pbootsma** [xlson/groovycsv#36]
I have a csv file from a customer that has an extra separator at the header row.
So the first line endsWith() a separator.
The parsing fails because it assumes an extra column in de data lines.

The file does import fine in LibreOffice

**Comment by xlson** [comment]
Hi @pbootsma,

Can you send me an example of this behaviour? I'm unable to reproduce it locally.

- Leonard

**Comment by pbootsma** [comment]
Hi Leonard,

Unfortunately I cannot send the file, it's processed and gone and will not
get a new one shortly.

I've been testing further and cannot reproduce either, there must have been
something else at play here.
I will ask my supplier for the file.
What I did notice was that an empty line (2 times enter) gives almost the
same error.

Thanks for looking at it.

2017-07-14 19:18 GMT+02:00 Leonard Gram <notifications@github.com>:

**Comment by xlson** [comment]
Hi,

Thanks for looking into it. If you're able to reproduce it I'd love to get an example. In the meantime this issue will be closed.

I'm not sure what version of GroovyCSV you are using but empty lines have unfortunately not been supported until recently and is only (currently) available in 1.2.1-SNAPSHOT. I will make a release of it soon.

- Leonard

**Comment by xlson** [comment]
It turns out I was wrong about empty lines being fully supported. Thanks for making me aware of this!

I've opened a new issue to handle the empty lines issue: #38
