### ISSUE TITLE
Cannot parse CSV as a closure from File.traverse

### ISSUE THREAD

**Issue by tyskjohan** [xlson/groovycsv#37]
```groovy
def dataDir = new File(".");

dataDir.traverse(type: FILES,  nameFilter: ~/.*\.csv$/) { File file ->
	file.withReader { Reader reader ->
		parseCsv(reader) { row ->
			println row
		}
	}
}
```

This fails because parseCsv does not provide a way to be called from a Closure:

`Caught: groovy.lang.MissingMethodException: No signature of method: static com.xlson.groovycsv.CsvParser.parseCsv() is applicable for argument types: (java.io.LineNumberReader, Dataload$_run_closure1$_closure3$_closure4)`

**Comment by xlson** [comment]
All you have to do to make your code work is to add a `.each` to your code and it will work perfectly.

Like this: `parseCsv(reader).each { row ->`

I could make it so calling parseCsv with a closure as one of its arguments would automatically iterate over the data but I'm not sure if it'd be a good idea or not.

**Comment by xlson** [comment]
I don't see any real advantage over calling .each explicitly so I will close this issue.
