### ISSUE TITLE
Empty lines aren't correctly skipped in 1.2.1-SNAPSHOT

### ISSUE THREAD

**Issue by xlson** [xlson/groovycsv#38]
Functionality to skip empty lines was implemented for 1.2.1-SNAPSHOT, unfortunately it's incomplete and code like the following will cause an exception to be thrown.

    @GrabResolver(name='snapshots', root='https://oss.sonatype.org/content/groups/public/')
    @Grab('com.xlson.groovycsv:groovycsv:1.2.1-SNAPSHOT')
    import static com.xlson.groovycsv.CsvParser.parseCsv
    
    def csv = parseCsv('''fruit,qty
    apple,5
    
    
    pear,6''')
    
    csv.eachWithIndex { it, index ->
    println index
    println it
    }

Output:

    0
    fruit: apple, qty: 5
    1
    Exception thrown
    
    java.lang.ArrayIndexOutOfBoundsException: 1
    	at com.xlson.groovycsv.PropertyMapper$_toString_closure1.doCall(PropertyMapper.groovy:67)
    	at com.xlson.groovycsv.PropertyMapper.toString(PropertyMapper.groovy:67)
    	at ConsoleScript28$_run_closure1.doCall(ConsoleScript28:13)
    	at ConsoleScript28.run(ConsoleScript28:11)

**Comment by xlson** [comment]
I was unable to reproduce this on my home machine which runs Groovy 1.8.x. Will upgrade to Groovy 2.6 and try again.

**Comment by xlson** [comment]
Was unable to reproduce with 2.4 as well but will take another look on the work computer tomorrow.

**Comment by xlson** [comment]
Unable to reproduce on my work computer either. Closing this until I have a repro case.

**Comment by jmonasteriotiq** [comment]
Turns out, I don't want to skip empty lines :(

**Comment by xlson** [comment]
@jmonasteriotiq Please create a new issue and describe your problem.
