### ISSUE TITLE
Use more up to date OpenCSV?

### ISSUE THREAD

**Issue by monetschemist** [xlson/groovycsv#39]
I've been using OpenCSV for awhile now and decided to give GroovyCSV a try.  It seems that GroovyCSV currently depends on a pretty old version of OpenCSV from au.com.bytecode.  I've tried changing the source to depend on the latest OpenCSV shown in Maven Central which today is 3.7 and from com.opencsv, as follows:

I've changed the imports in the src and test groovy files to

import com.opencsv.CSVReader

and also the build.gradle to

compile 'com.opencsv:opencsv:3.7'

Which gets me a clean build, but when I try to use the .jar file in the build/libs, I still get this error:

java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class com.xlson.groovycsv.CsvParser due to missing dependency au/com/bytecode/opencsv/CSVReader

Any thoughts on this?

**Comment by xlson** [comment]
Hi @monetschemist!

Thanks for making me aware that I was using an outdated version of opencsv.

It sounds like what you are doing should work. If you push an example project to GitHub using your custom lib I can take a look. I've created a branch (https://github.com/xlson/groovycsv/tree/feature/upgrade-opencsv-to-4.0) for migrating to 4.0 of opencsv and will try to release that shortly as groovycsv:1.3.

Cheers,
Leonard
