### ISSUE TITLE
Cannot parse double quote if is at the end of the line

### ISSUE THREAD

**Issue by karaabova** [xlson/groovycsv#42]
Hello,

I faced an issue, when trying to parse a file with a line that ends with quotes.
The parser doesn't read the ending quote, but if I add a char or space after the ending quote (line 1, from the file, ends with space), it is fine.

Let me share an example, a file with the following content:

id;test
1;project = "Test 1" 
2;project = "Test 2"

Code:
```
def data = parseCsv(new FileReader(new File("tmp.csv")), separator: ';')
 for(line in data) {
		println "$line"
}
```
Output:
```
id: 1, test: project = "Test 1" 
id: 2, test: project = "Test 2
```

**Comment by xlson** [comment]
Hi @karaabova,

Thanks for taking the time to describe your issue in detail, that makes it a lot easier for me to help.

The reason you're having problems is that `"` is the default quote char and is intended to surround everything between a separator and either another separator or the beginning/end of a line. What you can do is to simply set the quoteChar to something else, `:` for example.

This would work in your example:
```groovy
def data = parseCsv(new FileReader(new File("tmp.csv")), separator: ';', quoteChar: ':')
 for(line in data) {
		println "$line"
}
```

Hope this helps.
Cheers!
