### ISSUE TITLE
Improve configuration argument `skipLines` to support Ranges

### ISSUE THREAD

**Issue by GhaTMA** [xlson/groovycsv#44]
Improvement Request!

There is currently the possibility to `skipLines` using the configuration argument. But this reflects only a simple number for the first lines to be skipped. I suggest extending the definition of `skipLines` to support an array of single lines or Ranges of lines.
Current behaviour:
`skipLines: 10` would skip the first 10 Lines
Additional behaviour: 
`skipLines: [1..10, 15..16, 20, 22..24]` would skip the lines 1 to 10, 15, 16, 20 and 22 to 24.

**Comment by xlson** [comment]
Thanks for using GroovyCSV. I'm curious, what is the use case for this?

**Comment by GhaTMA** [comment]
I use CSV format to organize test cases and some batch executions. Each of the lines in CSV format means a single execution (one test case definition, or just one execution of a defined job). Some times I want to disable very specific lines (disable test cases, or executions). Now I delete the lines to do this. After the excution I restore the lines back. But with the requested feature, I will be able to actively define which lines to `ignore` without deleting them.

**Comment by xlson** [comment]
Interesting use case. I think it's a bit too esoteric for inclusion in GroovyCSV directly, but you should be able to "extend" it yourself by adding a skipping iterator you wrap the csv iterator with.
